# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Keg_Setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KegWindow(object):
    def setupUi(self, KegWindow):
        KegWindow.setObjectName("KegWindow")
        KegWindow.setWindowModality(QtCore.Qt.WindowModal)
        KegWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(KegWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("GrilledCheese BTN")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("GrilledCheese BTN")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxVisibleItems(3)
        self.comboBox.setObjectName("comboBox")
        KegWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KegWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        KegWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KegWindow)
        self.statusbar.setObjectName("statusbar")
        KegWindow.setStatusBar(self.statusbar)

        self.retranslateUi(KegWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(KegWindow)

    def retranslateUi(self, KegWindow):
        _translate = QtCore.QCoreApplication.translate
        KegWindow.setWindowTitle(_translate("KegWindow", "Keg Setup"))
        self.label.setText(_translate("KegWindow", "Keg Setup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KegWindow = QtWidgets.QMainWindow()
    ui = Ui_KegWindow()
    ui.setupUi(KegWindow)
    KegWindow.show()
    sys.exit(app.exec_())
